main: fr.doctorwho.service.API
name: DoctorWhoAPI
version: 1.0 alpha
authors: [Montras,Lasth]
commands:
    rank:
        description: Vous permet de mettre les grades aux joueurs
        aliases: grade 
    money:
        description: Vous permet de gérer votre argent
        aliases: solde